pipeline {
  agent {
    label 'built-in'
  }
  stages {
    stage('First'){
      steps {
        sh ''' echo "hello world">test.txt '''
      }
    }

    stage('Second'){
      steps {
        echo "HEY"
      }
    }
  }
}
