pipeline {
  agent {
    label 'local-agent'
  }
  environment {
    TARGET_ENV = 'DEV'
    DIR = 'HOME'
  }
  
  stages {
    stage('First'){
      steps {
        sh ''' echo "hello world !!!">test.txt 
        cat test.txt 
        echo "The environment is $TARGET_ENV"'''
      }
    }

    stage('Second'){
      steps {
        echo "HEY this is the directory: ${DIR}"
      }
    }
  }
}
