pipeline {
  agent {
    label 'local-agent'
  }
  environment {
    TARGET_ENV = 'DEV'
    DIR = 'HOME'
  }
  parameters {
    string(name: 'TEST_VARIABLE' ,defaultValue: 'TEST123')
    choice(name: 'USER', choices:['HH','ZZ'])
    booleanParam(name: 'DEPLOY_NOW', defaultValue: false)
  }
  stages {
    stage('First'){
      when {
        branch 'dev'
      }
      steps {
        sh ''' echo "hello world !!!">test.txt 
        cat test.txt 
        echo "The environment is $TARGET_ENV"'''
        stash includes: 'test.txt', name: 'my-stash'
      }
    }

    stage('Second'){
      steps {
        echo "---UNSTASHING NOW test.txt---"
        unstash 'my-stash'
        sh ''' cat test.txt'''
      }
    }
  }
  post {
    success {echo "Success"}
    failure {echo "Failure"}
    always {echo "....STAGES DONE...."}
  }
}
